ActiveSupport::Inflector.inflections(:en) do |inflect|
  inflect.irregular 'funcao', 'funcoes'
  inflect.irregular 'unidade', 'unidades'
  inflect.irregular 'tipo_unidade', 'tipo_unidades'
  inflect.irregular 'cargo', 'cargos'
  inflect.irregular 'motorista', 'motoristas'
  inflect.irregular 'veiculo', 'veiculos'
  inflect.irregular 'requisicao_transporte', 'requisicao_transportes'
  inflect.irregular 'passageiro', 'passageiros'
  inflect.irregular 'destino', 'destinos'
  inflect.irregular 'servico_transporte', 'servico_transportes'
  inflect.irregular 'requisicao_ti', 'requisicao_tis'
  inflect.irregular 'problema_ti', 'problema_tis'
  inflect.irregular 'tipo_problema_ti', 'tipo_problema_tis'
  inflect.irregular 'mensagem', 'mensagens'
end
