# config/database.yml

development:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: 12345678
  database: siscom_development
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

test:
  adapter: postgresql
  encoding: unicode
  host: localhost
  port: 5432
  username: postgres
  password: 12345678
  database: siscom_test
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>

# Em produção (Dokku) use a variável DATABASE_URL
production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  url: <%= ENV["DATABASE_URL"] %>
